(dl4cv) [kaustubhj@kaustubh-pc ~]$ cd project
(dl4cv) [kaustubhj@kaustubh-pc project]$ python train_network.py --dataset goldfish --model goldfish.model
Using TensorFlow backend.
2020-03-18 12:30:25.816096: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:30:25.816248: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:30:25.816270: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "train_network.py", line 14, in <module>
    from pyimagesearch.lenet import LeNet
ModuleNotFoundError: No module named 'pyimagesearch'
(dl4cv) [kaustubhj@kaustubh-pc project]$ python train_network.py --dataset goldfish --model goldfish.model
Using TensorFlow backend.
2020-03-18 12:32:01.733818: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:32:01.733965: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:32:01.733988: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[INFO] loading images...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[INFO] compiling model...
2020-03-18 12:32:34.052688: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-03-18 12:32:34.052746: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-18 12:32:34.052782: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kaustubh-pc): /proc/driver/nvidia/version does not exist
2020-03-18 12:32:34.053175: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-18 12:32:34.139278: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1996845000 Hz
2020-03-18 12:32:34.150525: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d08b702e10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-18 12:32:34.150619: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[INFO] training network...
Epoch 1/25
2020-03-18 12:32:36.275171: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 23520000 exceeds 10% of system memory.
2020-03-18 12:32:36.275229: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 23520000 exceeds 10% of system memory.
2020-03-18 12:32:36.298244: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 24460800 exceeds 10% of system memory.
 1/19 [>.............................] - ETA: 11s - loss: 0.7110 - accuracy: 0.31252020-03-18 12:32:36.367092: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 23520000 exceeds 10% of system memory.
2020-03-18 12:32:36.367099: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 23520000 exceeds 10% of system memory.
19/19 [==============================] - 2s 115ms/step - loss: 0.6231 - accuracy: 0.6910 - val_loss: 0.4383 - val_accuracy: 0.7343
Epoch 2/25
19/19 [==============================] - 2s 81ms/step - loss: 0.3905 - accuracy: 0.7997 - val_loss: 0.3466 - val_accuracy: 0.8454
Epoch 3/25
19/19 [==============================] - 1s 78ms/step - loss: 0.3688 - accuracy: 0.8302 - val_loss: 0.2552 - val_accuracy: 0.9179
Epoch 4/25
19/19 [==============================] - 2s 79ms/step - loss: 0.2998 - accuracy: 0.8586 - val_loss: 0.2583 - val_accuracy: 0.9082
Epoch 5/25
19/19 [==============================] - 1s 78ms/step - loss: 0.3196 - accuracy: 0.8667 - val_loss: 0.2267 - val_accuracy: 0.9227
Epoch 6/25
19/19 [==============================] - 1s 73ms/step - loss: 0.2500 - accuracy: 0.8849 - val_loss: 0.1746 - val_accuracy: 0.9275
Epoch 7/25
19/19 [==============================] - 1s 76ms/step - loss: 0.2078 - accuracy: 0.9158 - val_loss: 0.1982 - val_accuracy: 0.9372
Epoch 8/25
19/19 [==============================] - 1s 73ms/step - loss: 0.2329 - accuracy: 0.8846 - val_loss: 0.1958 - val_accuracy: 0.9275
Epoch 9/25
19/19 [==============================] - 1s 78ms/step - loss: 0.2263 - accuracy: 0.8947 - val_loss: 0.1667 - val_accuracy: 0.9420
Epoch 10/25
19/19 [==============================] - 1s 75ms/step - loss: 0.1907 - accuracy: 0.9083 - val_loss: 0.1598 - val_accuracy: 0.9372
Epoch 11/25
19/19 [==============================] - 1s 73ms/step - loss: 0.2019 - accuracy: 0.9185 - val_loss: 0.1507 - val_accuracy: 0.9372
Epoch 12/25
19/19 [==============================] - 1s 78ms/step - loss: 0.1405 - accuracy: 0.9408 - val_loss: 0.1614 - val_accuracy: 0.9372
Epoch 13/25
19/19 [==============================] - 1s 74ms/step - loss: 0.1517 - accuracy: 0.9406 - val_loss: 0.1448 - val_accuracy: 0.9372
Epoch 14/25
19/19 [==============================] - 1s 72ms/step - loss: 0.1672 - accuracy: 0.9263 - val_loss: 0.2292 - val_accuracy: 0.9420
Epoch 15/25
19/19 [==============================] - 2s 80ms/step - loss: 0.1668 - accuracy: 0.9243 - val_loss: 0.1600 - val_accuracy: 0.9372
Epoch 16/25
19/19 [==============================] - 1s 73ms/step - loss: 0.1659 - accuracy: 0.9304 - val_loss: 0.1397 - val_accuracy: 0.9324
Epoch 17/25
19/19 [==============================] - 1s 74ms/step - loss: 0.1445 - accuracy: 0.9406 - val_loss: 0.1431 - val_accuracy: 0.9372
Epoch 18/25
19/19 [==============================] - 1s 75ms/step - loss: 0.1612 - accuracy: 0.9338 - val_loss: 0.1707 - val_accuracy: 0.9324
Epoch 19/25
19/19 [==============================] - 1s 74ms/step - loss: 0.1778 - accuracy: 0.9236 - val_loss: 0.1218 - val_accuracy: 0.9517
Epoch 20/25
19/19 [==============================] - 1s 72ms/step - loss: 0.1234 - accuracy: 0.9440 - val_loss: 0.1260 - val_accuracy: 0.9517
Epoch 21/25
19/19 [==============================] - 1s 72ms/step - loss: 0.1181 - accuracy: 0.9474 - val_loss: 0.1130 - val_accuracy: 0.9372
Epoch 22/25
19/19 [==============================] - 1s 75ms/step - loss: 0.1111 - accuracy: 0.9440 - val_loss: 0.1284 - val_accuracy: 0.9517
Epoch 23/25
19/19 [==============================] - 1s 74ms/step - loss: 0.1028 - accuracy: 0.9593 - val_loss: 0.1298 - val_accuracy: 0.9565
Epoch 24/25
19/19 [==============================] - 1s 74ms/step - loss: 0.1117 - accuracy: 0.9508 - val_loss: 0.1373 - val_accuracy: 0.9469
Epoch 25/25
19/19 [==============================] - 1s 75ms/step - loss: 0.0926 - accuracy: 0.9626 - val_loss: 0.1352 - val_accuracy: 0.9565
[INFO] serializing network...
Traceback (most recent call last):
  File "train_network.py", line 104, in <module>
    plt.plot(np.arange(0, N), H.history["acc"], label="train_acc")
KeyError: 'acc'
(dl4cv) [kaustubhj@kaustubh-pc project]$ python test_network.py --model goldfish.model --image /goldfish/goldfish/00000011.jpg
Using TensorFlow backend.
2020-03-18 12:37:53.690338: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:37:53.690506: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:37:53.690531: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "test_network.py", line 22, in <module>
    orig = image.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
(dl4cv) [kaustubhj@kaustubh-pc project]$ python test_network.py --model goldfish.model --image goldfish/goldfish/00000011.jpg
Using TensorFlow backend.
2020-03-18 12:38:22.099162: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:38:22.099303: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:38:22.099327: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[INFO] loading network...
2020-03-18 12:38:23.220438: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-03-18 12:38:23.220504: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-18 12:38:23.220541: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kaustubh-pc): /proc/driver/nvidia/version does not exist
2020-03-18 12:38:23.220890: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-18 12:38:23.249412: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1996845000 Hz
2020-03-18 12:38:23.250831: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555aafe69480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-18 12:38:23.250881: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(dl4cv) [kaustubhj@kaustubh-pc project]$ python test_network.py --model goldfish.model --image goldfish/not_goldfish/00000021.jpg 
Using TensorFlow backend.
2020-03-18 12:44:41.526766: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:44:41.526905: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-18 12:44:41.526930: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[INFO] loading network...
2020-03-18 12:44:42.602151: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-03-18 12:44:42.602217: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-18 12:44:42.602292: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kaustubh-pc): /proc/driver/nvidia/version does not exist
2020-03-18 12:44:42.602653: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-18 12:44:42.632479: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1996845000 Hz
2020-03-18 12:44:42.633372: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561c949ac020 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-18 12:44:42.633417: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
